[window]
decorations = "Full" # "None"
option_as_alt = "OnlyRight"

[scrolling]
history = 100000

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Medium" }
italic = { family = "SauceCodePro Nerd Font Mono", style = "Italic" }
bold_italic = { family = "SauceCodePro Nerd Font Mono", style = "SemiBold Italic" }
size = 14
builtin_box_drawing = true

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = false
