[window]
decorations = "Full"
option_as_alt = "OnlyRight"
padding.x = 0
padding.y = 0

[scrolling]
history = 100000

[font]
normal = { family = "MesloLGL Nerd Font", style = "Regular" }
bold = { family = "MesloLGL Nerd Font", style = "Bold" }
italic = { family = "MesloLGL Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGL Nerd Font", style = "Bold Italic" }
size = 13
offset = { x = 0, y = -4 }
builtin_box_drawing = true

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = false
