# [terminal.shell]
# program = "/opt/homebrew/bin/bash"

[window]
decorations = "Full"
option_as_alt = "OnlyRight"

[scrolling]
history = 100000

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Medium" }
italic = { family = "SauceCodePro Nerd Font Mono", style = "Italic" }
bold_italic = { family = "SauceCodePro Nerd Font Mono", style = "SemiBold Italic" }
size = 12
builtin_box_drawing = true

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = false
